name: Main workflow 2
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #### Добавьте шаг с Flyway-миграциями
    - name: Set up Flyway
      run: |
        curl -L -o flyway-commandline.tar.gz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz"
        tar -xzf flyway-commandline.tar.gz
        sudo ln -s \`pwd\`/flyway-11.1.0/flyway /usr/local/bin/flyway
    - name: Run Flyway migrations
      run: |
        flyway migrate -configFiles="flyway.conf"
    ### Этот шаг оставьте без изменений
    - name: Download and setup autotests binaries
      run: |
        flyway migrate -configFiles="flyway_conf/testing.conf"

    ### Этот шаг оставьте без изменений
    - name: Test
      run: |
        dbopstest \
          -test.v \
          -host=${{ secrets.DB_HOST }} \
          -port=${{ secrets.DB_PORT }} \
          -user=${{ secrets.DB_USER }} \
          -password=${{ secrets.DB_PASSWORD }} \
          -db=${{ secrets.DB_NAME }}
